#!/bin/bash -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if which update-icon-caches >/dev/null 2>&1 ; then
		update-icon-caches /usr/share/icons/Mint-Y-Mono /usr/share/icons/Mint-Y-Mono-Aqua /usr/share/icons/Mint-Y-Mono-Blue /usr/share/icons/Mint-Y-Mono-Brown /usr/share/icons/Mint-Y-Mono-Grey /usr/share/icons/Mint-Y-Mono-Orange /usr/share/icons/Mint-Y-Mono-Pink /usr/share/icons/Mint-Y-Mono-Purple /usr/share/icons/Mint-Y-Mono-Red /usr/share/icons/Mint-Y-Mono-Sand /usr/share/icons/Mint-Y-Mono-Teal
	fi
fi
#DEBHELPER#
